# Generated by Django 3.1 on 2021-12-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0003_remove_brand_stock"),
        ("store", "0010_reviewrating"),
        ("banners", "0001_initial"),
    ]

    operations = [migrations.RenameModel(old_name="Banners", new_name="Banner")]
