# Generated by Django 3.1 on 2021-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="stock",
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
