# Generated by Django 3.1 on 2021-11-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="images", new_name="image1"
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(default=1, upload_to="photos/products"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(default=2, upload_to="photos/products"),
            preserve_default=False,
        ),
    ]
