# Generated by Django 3.1 on 2021-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0003_variation")]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("memory", "memory")], max_length=100
            ),
        )
    ]
