# Generated by Django 3.1 on 2021-11-25 13:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0004_auto_20211118_0708")]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=colorfield.fields.ColorField(default="#FF0000", max_length=18),
        )
    ]
