# Generated by Django 3.1 on 2021-11-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0008_auto_20211126_1129")]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(choices=[("color", "Color")], max_length=100),
        )
    ]
