# Generated by Django 3.1 on 2021-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("store", "0010_reviewrating")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=900),
        )
    ]
