# Generated by Django 3.1 on 2021-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20211118_0708"),
        ("carts", "0002_auto_20211117_0938"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.Variation"),
        )
    ]
