# Generated by Django 3.1 on 2021-11-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brand", "0003_remove_brand_stock"),
        ("category", "0008_auto_20211116_0826"),
        ("store", "0009_auto_20211127_0516"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_offer",
                    models.PositiveBigIntegerField(help_text="Offer in percentage"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_offer",
                    models.PositiveBigIntegerField(help_text="Offer in percentage"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BrandOffer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_offer",
                    models.PositiveBigIntegerField(help_text="Offer in percentage"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brand.brand",
                    ),
                ),
            ],
        ),
    ]
