# Generated by Django 3.1 on 2021-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("offer", "0002_coupon_redeemedcoupon")]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="limit",
            field=models.PositiveIntegerField(null=True),
        )
    ]
