# Generated by Django 3.1 on 2021-11-29 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_userprofile")]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50, unique=True)),
                ("phone_number", models.CharField(max_length=50, unique=True)),
                ("address_line", models.CharField(blank=True, max_length=100)),
                (
                    "house_no",
                    models.CharField(
                        max_length=255, verbose_name="House no/Building/Company"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=20)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=20)),
                ("pin", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        help_text="Example:- Home, Office, etc",
                        max_length=50,
                        null=True,
                        verbose_name="Address Type",
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
