# Generated by Django 3.1 on 2021-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_address")]

    operations = [
        migrations.AlterField(
            model_name="address", name="email", field=models.CharField(max_length=50)
        ),
        migrations.AlterField(
            model_name="address",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
    ]
