# Generated by Django 3.1 on 2021-11-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("category", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "category"},
        )
    ]
