# Generated by Django 3.1 on 2021-11-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("category", "0002_auto_20211112_0809")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        )
    ]
