# Generated by Django 3.1 on 2021-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0004_auto_20211112_0903")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        )
    ]
