# Generated by Django 3.1 on 2021-11-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0005_auto_20211112_1354")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        )
    ]
