# Generated by Django 3.1 on 2021-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0006_auto_20211113_0346")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(unique=True, upload_to="photots/categories"),
        )
    ]
