# Generated by Django 3.1 on 2021-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("category", "0007_auto_20211116_0825")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="photots/categories"),
        )
    ]
