# Generated by Django 3.1 on 2021-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        )
    ]
