# Generated by Django 3.1 on 2021-11-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0003_auto_20211120_1731")]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_line_1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
