# Generated by Django 3.1 on 2021-11-22 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0004_auto_20211120_1912")]

    operations = [
        migrations.RenameField(
            model_name="orderproduct", old_name="orderd", new_name="ordered"
        )
    ]
