# Generated by Django 3.1 on 2021-11-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orders", "0006_auto_20211122_1356")]

    operations = [
        migrations.RenameField(
            model_name="orderproduct", old_name="Order", new_name="order"
        )
    ]
