# Generated by Django 3.1 on 2021-11-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0009_auto_20211122_1410")]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Placed", "Placed"),
                    ("Shipped", "Shipped"),
                    ("Accepted", "Accepted"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                ],
                default="New",
                max_length=10,
            ),
        )
    ]
