# Generated by Django 3.1 on 2021-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orders", "0010_orderproduct_status")]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="discount",
            field=models.FloatField(default=0),
        )
    ]
